_target_: fastwam.runtime.create_fastwam_one
model_id: Wan-AI/Wan2.2-TI2V-5B
tokenizer_model_id: Wan-AI/Wan2.1-T2V-1.3B
tokenizer_max_len: 128
load_text_encoder: false
proprio_dim: ${data.train.processor.proprio_output_dim}
redirect_common_files: true
video_action_dit_pretrained_path: checkpoints/WanVideoActionDiT_partial_init_Wan22.pt
skip_dit_load_from_pretrain: false
action_per_frame: null

video_action_dit_config:
  has_image_input: false
  patch_size: [1, 2, 2]
  in_dim: 48
  hidden_dim: 3072
  ffn_dim: 14336
  freq_dim: 256
  text_dim: 4096
  out_dim: 48
  num_heads: 24
  attn_head_dim: 128
  num_layers: 30
  eps: 1.0e-06
  seperated_timestep: true
  require_clip_embedding: false
  require_vae_embedding: false
  fuse_vae_embedding_in_latents: true
  action_dim: ${data.train.processor.action_output_dim}
  rope_max_seq_len: 1024
  rope_theta: 10000.0
  use_gradient_checkpointing: true

video_scheduler:
  train_shift: 5.0
  infer_shift: 5.0
  num_train_timesteps: 1000

action_scheduler:
  train_shift: 5.0
  infer_shift: 5.0
  num_train_timesteps: 1000

loss:
  lambda_video: 1.0
  lambda_depth: 1.0
  lambda_action: 1.0
